# Generated by Django 5.1.1 on 2024-10-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ddescription',
            new_name='description',
        ),
    ]
