# Generated by Django 5.1 on 2024-09-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
    ]
